const encoder = new TextEncoder();
const CATEGORY = new Set(['new', 'used']);
const STATUS = new Set(['in_stock', 'incoming', 'sold', 'reserved']);
const LEAD_TYPES = new Set(['consultation', 'order', 'finance']);
const MIME = { jpg: 'image/jpeg', jpeg: 'image/jpeg', png: 'image/png', webp: 'image/webp', avif: 'image/avif' };
const SETTINGS_DEFAULTS = {
  store_name: 'TÂM AN', store_location: 'NOMURA • HẢI PHÒNG', hotline: '0856 262 886',
  zalo_link: 'https://zalo.me/0856262886', facebook_link: '', messenger_link: '', tiktok_link: '', youtube_link: '', contact_email: '',
  address: 'Cổng phụ KCN Nomura, Hải Phòng',
  map_link: 'https://maps.google.com/?q=Cổng+phụ+KCN+Nomura+Hải+Phòng',
  map_embed: 'https://www.google.com/maps?q=C%E1%BB%95ng%20ph%E1%BB%A5%20KCN%20Nomura%20H%E1%BA%A3i%20Ph%C3%B2ng&output=embed',
  primary_color: '#b80f19', paper_color: '#f8f6f5', dark_color: '#1b1112', font_family: 'Be Vietnam Pro', heading_font: 'Barlow Condensed',
  site_title: 'Xe Máy Tâm An Nomura | Xe mới, xe cũ & trả góp Hải Phòng', logo_image: '', favicon_image: '',
  topline: 'TRẢ GÓP LINH HOẠT • HỒ SƠ NHANH • XE MỚI VÀ XE CŨ TUYỂN CHỌN',
  hero_eyebrow: 'Xe máy Tâm An Nomura', hero_title: 'Chọn xe ưng ý.', hero_highlight: 'Lên đường an tâm.',
  hero_description: 'Xe mới chính hãng, xe cũ tuyển chọn. Hỗ trợ trả góp nhanh, thủ tục rõ ràng và chăm sóc tận tâm tại Hải Phòng.', hero_image: '',
  inventory_eyebrow: 'Kho xe Tâm An', inventory_title: 'Xe đang chờ\nbạn cầm lái.', inventory_description: 'Vuốt ngang để xem nhiều xe hơn. Chạm vào xe để xem chi tiết và nhận tư vấn.',
  delivery_title: 'Hỗ trợ giao xe tận nơi', delivery_description: 'Tâm An kiểm tra khu vực giao xe, thời gian nhận xe và chi phí rõ ràng trước khi hẹn giao.',
  cta_eyebrow: 'TÂM AN NOMURA', cta_title: 'Xe đã chọn xong.\nChỉ còn cuộc gọi của bạn.'
};
let schemaPromise;
function json(data, init = {}) { const headers = new Headers(init.headers || {}); headers.set('content-type','application/json; charset=utf-8'); headers.set('cache-control',headers.get('cache-control')||'no-store'); return new Response(JSON.stringify(data),{...init,headers}); }
function error(message,status=400){return json({ok:false,error:message},{status});}
function cleanText(value,fallback=''){return typeof value==='string'?value.trim().slice(0,5000):fallback;}
function nullableNumber(value){if(value===''||value===null||value===undefined)return null;const number=Number(value);return Number.isFinite(number)&&number>=0?Math.round(number):null;}
function safeBool(value, fallback=false){return value===true||value==='true'||value==='on'||value===1||value==='1'?true:fallback;}
function slugify(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,100)||`xe-${Date.now()}`;}
function parseImages(value){try{const data=Array.isArray(value)?value:JSON.parse(value||'[]');return Array.isArray(data)?data.filter(item=>typeof item==='string'&&item.length<1000).slice(0,12):[];}catch{return [];}}
function parseColorVariants(value){try{const data=Array.isArray(value)?value:JSON.parse(value||'[]');if(!Array.isArray(data))return [];return data.map(item=>{const name=cleanText(item?.name).slice(0,80);const hex=/^#[0-9a-f]{6}$/i.test(String(item?.hex||''))?String(item.hex).toLowerCase():'#7a7a7a';const image=cleanText(item?.image||item?.image_url).slice(0,1000);return {name,hex,image};}).filter(item=>item.name&&item.image).slice(0,20);}catch{return [];}}
function rowToBike(row){const images=parseImages(row.images);let color_variants=parseColorVariants(row.color_variants);if(!color_variants.length&&row.color&&images[0])color_variants=[{name:String(row.color).split(',')[0].trim()||'Màu sẵn có',hex:'#7a7a7a',image:images[0]}];return {...row,images,color_variants,featured:Boolean(row.featured),show_price:row.show_price===null||row.show_price===undefined?true:Boolean(row.show_price),installment_from:Number(row.installment_from||0),bad_debt_down_payment:Number(row.bad_debt_down_payment||0)};}
function rowToPromotion(row){return {...row,active:Boolean(row.active)};}
function rowToAccessory(row){return {...row,active:Boolean(row.active)};}
function cookies(request){return Object.fromEntries((request.headers.get('cookie')||'').split(';').map(item=>item.trim().split('=').map(decodeURIComponent)).filter(([key])=>key));}
function base64Url(bytes){let string='';for(const byte of bytes)string+=String.fromCharCode(byte);return btoa(string).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');}
async function sign(value,secret){const key=await crypto.subtle.importKey('raw',encoder.encode(secret||''),{name:'HMAC',hash:'SHA-256'},false,['sign']);return base64Url(new Uint8Array(await crypto.subtle.sign('HMAC',key,encoder.encode(value))));}
async function createSession(secret,payload){const token=base64Url(encoder.encode(JSON.stringify({...payload,exp:Date.now()+12*60*60*1000})));return `${token}.${await sign(token,secret)}`;}
async function getSession(request,env){const token=cookies(request).tam_an_admin;if(!token||!env.SESSION_SECRET)return null;const [payload,signature]=token.split('.');if(!payload||!signature||signature!==await sign(payload,env.SESSION_SECRET))return null;try{const decoded=atob(payload.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(payload.length/4)*4,'='));const session=JSON.parse(new TextDecoder().decode(Uint8Array.from(decoded,c=>c.charCodeAt(0))));return session.exp>Date.now()?session:null;}catch{return null;}}
async function passwordHash(password,secret){const bytes=await crypto.subtle.digest('SHA-256',encoder.encode(`${secret}|tam-an-staff|${password}`));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function parseJson(request){try{return await request.json();}catch{return null;}}
function hasRole(session,role){return Boolean(session?.role===role);}
async function requireSession(request,env){const session=await getSession(request,env);return session||null;}
async function addColumn(env,table,column,definition){try{const result=await env.DB.prepare(`PRAGMA table_info(${table})`).all();if(!(result.results||[]).some(item=>item.name===column))await env.DB.prepare(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`).run();}catch(cause){if(!String(cause?.message||cause).toLowerCase().includes('duplicate column'))throw cause;}}
async function ensureSchema(env){if(schemaPromise)return schemaPromise;schemaPromise=(async()=>{
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS bikes (
    id INTEGER PRIMARY KEY AUTOINCREMENT, slug TEXT UNIQUE NOT NULL, name TEXT NOT NULL, brand TEXT NOT NULL DEFAULT 'Honda', category TEXT NOT NULL DEFAULT 'new', price INTEGER NOT NULL DEFAULT 0, msrp INTEGER, year INTEGER, mileage INTEGER, engine TEXT, color TEXT, documents TEXT, status TEXT NOT NULL DEFAULT 'in_stock', description TEXT, images TEXT NOT NULL DEFAULT '[]', color_variants TEXT NOT NULL DEFAULT '[]', featured INTEGER NOT NULL DEFAULT 0, sort_order INTEGER NOT NULL DEFAULT 0, installment_from INTEGER NOT NULL DEFAULT 0, bad_debt_down_payment INTEGER NOT NULL DEFAULT 0, show_price INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`).run();
  const columns=await env.DB.prepare('PRAGMA table_info(bikes)').all();const existing=new Set((columns.results||[]).map(c=>c.name));
  for(const sql of [
    ['installment_from','ALTER TABLE bikes ADD COLUMN installment_from INTEGER NOT NULL DEFAULT 0'],['bad_debt_down_payment','ALTER TABLE bikes ADD COLUMN bad_debt_down_payment INTEGER NOT NULL DEFAULT 0'],['show_price','ALTER TABLE bikes ADD COLUMN show_price INTEGER NOT NULL DEFAULT 1'],['color_variants',"ALTER TABLE bikes ADD COLUMN color_variants TEXT NOT NULL DEFAULT '[]'"]
  ]) if(!existing.has(sql[0])) await env.DB.prepare(sql[1]).run();
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS site_settings (id INTEGER PRIMARY KEY CHECK(id=1), data TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  await env.DB.prepare('INSERT OR IGNORE INTO site_settings (id,data) VALUES (1,?)').bind(JSON.stringify(SETTINGS_DEFAULTS)).run();
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS leads (id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT NOT NULL DEFAULT 'consultation',name TEXT NOT NULL,phone TEXT NOT NULL,bike_name TEXT,down_payment TEXT,credit_status TEXT,note TEXT,status TEXT NOT NULL DEFAULT 'new',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  await env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_leads_created ON leads(created_at DESC)').run();
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS promotions (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,description TEXT NOT NULL,image_url TEXT,active INTEGER NOT NULL DEFAULT 1,sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS accessories (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,category TEXT NOT NULL DEFAULT 'Phụ kiện',price INTEGER NOT NULL DEFAULT 0,description TEXT,image_url TEXT,active INTEGER NOT NULL DEFAULT 1,sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS staff_accounts (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS conversations (id TEXT PRIMARY KEY,visitor_id TEXT UNIQUE NOT NULL,visitor_name TEXT,last_message TEXT,last_message_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,visitor_unread INTEGER NOT NULL DEFAULT 0,staff_unread INTEGER NOT NULL DEFAULT 0,assigned_staff_name TEXT,assigned_staff_id INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS chat_messages (id INTEGER PRIMARY KEY AUTOINCREMENT,conversation_id TEXT NOT NULL,sender TEXT NOT NULL,sender_name TEXT,staff_id INTEGER,message TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  await addColumn(env,'conversations','staff_unread','INTEGER NOT NULL DEFAULT 0');
  await addColumn(env,'conversations','assigned_staff_name','TEXT');
  await addColumn(env,'conversations','assigned_staff_id','INTEGER');
  await addColumn(env,'chat_messages','sender_name','TEXT');
  await addColumn(env,'chat_messages','staff_id','INTEGER');
  await env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_chat_messages_conversation ON chat_messages(conversation_id,id)').run();
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS analytics_visits (id INTEGER PRIMARY KEY AUTOINCREMENT,day TEXT NOT NULL,visitor_hash TEXT NOT NULL,path TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  await env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_analytics_day ON analytics_visits(day)').run();
})().catch(cause=>{schemaPromise=undefined;throw cause;});return schemaPromise;}
async function getSettings(env){await ensureSchema(env);const row=await env.DB.prepare('SELECT data FROM site_settings WHERE id=1').first();try{return {...SETTINGS_DEFAULTS,...(row?JSON.parse(row.data):{})};}catch{return {...SETTINGS_DEFAULTS};}}
function normalizeSettings(payload={}){const settings={...SETTINGS_DEFAULTS};for(const key of Object.keys(SETTINGS_DEFAULTS))settings[key]=cleanText(payload[key],SETTINGS_DEFAULTS[key]);for(const color of ['primary_color','paper_color','dark_color'])if(!/^#[0-9a-f]{6}$/i.test(settings[color]))settings[color]=SETTINGS_DEFAULTS[color];if(!['Be Vietnam Pro','Plus Jakarta Sans','Sora','Manrope','DM Sans','Montserrat'].includes(settings.font_family))settings.font_family=SETTINGS_DEFAULTS.font_family;if(!['Barlow Condensed','Montserrat','Sora','Space Grotesk','Be Vietnam Pro'].includes(settings.heading_font))settings.heading_font=SETTINGS_DEFAULTS.heading_font;return settings;}
function normalizeBike(payload,existing={}){const name=cleanText(payload.name);const color_variants=parseColorVariants(payload.color_variants);const color=cleanText(payload.color)||color_variants.map(item=>item.name).join(', ');return {slug:slugify(payload.slug||name||existing.name),name,brand:cleanText(payload.brand,'Honda')||'Honda',category:CATEGORY.has(payload.category)?payload.category:'new',status:STATUS.has(payload.status)?payload.status:'in_stock',price:nullableNumber(payload.price)||0,msrp:nullableNumber(payload.msrp),year:nullableNumber(payload.year),mileage:nullableNumber(payload.mileage),engine:cleanText(payload.engine),color,documents:cleanText(payload.documents),description:cleanText(payload.description),installment_from:nullableNumber(payload.installment_from)||0,bad_debt_down_payment:nullableNumber(payload.bad_debt_down_payment)||0,featured:safeBool(payload.featured)?1:0,show_price:safeBool(payload.show_price)?1:0,sort_order:nullableNumber(payload.sort_order)||0,images:parseImages(payload.images),color_variants};}
function normalizePromo(payload={}){return {title:cleanText(payload.title),description:cleanText(payload.description),image_url:cleanText(payload.image_url),active:safeBool(payload.active)?1:0,sort_order:nullableNumber(payload.sort_order)||0};}
function normalizeAccessory(payload={}){return {name:cleanText(payload.name),category:cleanText(payload.category,'Phụ kiện')||'Phụ kiện',price:nullableNumber(payload.price)||0,description:cleanText(payload.description),image_url:cleanText(payload.image_url),active:safeBool(payload.active)?1:0,sort_order:nullableNumber(payload.sort_order)||0};}
async function notifyLead(env,lead,settings){const to=env.LEADS_EMAIL||settings.contact_email;if(!env.RESEND_API_KEY||!to)return false;const label=lead.type==='finance'?'Tư vấn trả góp':lead.type==='order'?'Đặt xe / giữ xe':'Yêu cầu tư vấn';const body=[`Loại yêu cầu: ${label}`,`Khách hàng: ${lead.name}`,`Số điện thoại: ${lead.phone}`,`Xe quan tâm: ${lead.bike_name||'Chưa chọn'}`,`Trả trước dự kiến: ${lead.down_payment||'Chưa rõ'}`,`Tình trạng hồ sơ: ${lead.credit_status||'Chưa rõ'}`,`Ghi chú: ${lead.note||'Không có'}`].join('\n');try{const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${env.RESEND_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({from:env.EMAIL_FROM||'Tâm An Website <onboarding@resend.dev>',to:[to],subject:`[Tâm An] ${label} từ ${lead.name}`,text:body})});return response.ok;}catch{return false;}}
function dayNow(){return new Date().toISOString().slice(0,10);}
async function getOrCreateConversation(env,visitorId){let conversation=await env.DB.prepare('SELECT * FROM conversations WHERE visitor_id=?').bind(visitorId).first();if(conversation)return conversation;const id=crypto.randomUUID();await env.DB.prepare('INSERT INTO conversations (id,visitor_id,last_message,last_message_at) VALUES (?,?,?,CURRENT_TIMESTAMP)').bind(id,visitorId,'').run();return await env.DB.prepare('SELECT * FROM conversations WHERE id=?').bind(id).first();}
function validVisitorId(value){return typeof value==='string'&&value.length>=8&&value.length<100;}
async function handlePublic(request,env,url){const path=url.pathname;
  if(path==='/api/settings'&&request.method==='GET')return json({ok:true,settings:await getSettings(env)},{headers:{'cache-control':'public, max-age=60'}});
  if(path==='/api/bikes'&&request.method==='GET'){const status=url.searchParams.get('status'),category=url.searchParams.get('category'),terms=[],values=[];if(STATUS.has(status)){terms.push('status=?');values.push(status);}if(CATEGORY.has(category)){terms.push('category=?');values.push(category);}const statement=env.DB.prepare(`SELECT * FROM bikes ${terms.length?`WHERE ${terms.join(' AND ')}`:''} ORDER BY featured DESC,sort_order ASC,id DESC`);const result=values.length?await statement.bind(...values).all():await statement.all();return json({ok:true,bikes:(result.results||[]).map(rowToBike)},{headers:{'cache-control':'public,max-age=60'}});}
  if(path==='/api/promotions'&&request.method==='GET'){const result=await env.DB.prepare('SELECT * FROM promotions WHERE active=1 ORDER BY sort_order ASC,id DESC').all();return json({ok:true,promotions:(result.results||[]).map(rowToPromotion)});}
  if(path==='/api/accessories'&&request.method==='GET'){const result=await env.DB.prepare('SELECT * FROM accessories WHERE active=1 ORDER BY sort_order ASC,id DESC').all();return json({ok:true,accessories:(result.results||[]).map(rowToAccessory)});}
  if(path==='/api/leads'&&request.method==='POST'){const payload=await parseJson(request);if(!payload)return error('Dữ liệu không hợp lệ.');const lead={type:LEAD_TYPES.has(payload.type)?payload.type:'consultation',name:cleanText(payload.name),phone:cleanText(payload.phone),bike_name:cleanText(payload.bike_name),down_payment:cleanText(payload.down_payment),credit_status:cleanText(payload.credit_status),note:cleanText(payload.note)};if(!lead.name||!lead.phone)return error('Vui lòng nhập họ tên và số điện thoại.');await env.DB.prepare('INSERT INTO leads (type,name,phone,bike_name,down_payment,credit_status,note) VALUES (?,?,?,?,?,?,?)').bind(lead.type,lead.name,lead.phone,lead.bike_name,lead.down_payment,lead.credit_status,lead.note).run();const settings=await getSettings(env);return json({ok:true,email_sent:await notifyLead(env,lead,settings)},{status:201});}
  if(path==='/api/analytics/view'&&request.method==='POST'){const payload=await parseJson(request);const visitor=cleanText(payload?.visitor_id).slice(0,100);const page=cleanText(payload?.path,'/').slice(0,180);if(visitor)await env.DB.prepare('INSERT INTO analytics_visits(day,visitor_hash,path) VALUES (?,?,?)').bind(dayNow(),visitor,page).run();return json({ok:true},{status:201});}
  if(path==='/api/chat/messages'&&request.method==='GET'){const visitorId=url.searchParams.get('visitor_id');if(!validVisitorId(visitorId))return json({ok:true,messages:[],conversation:null});const conversation=await env.DB.prepare('SELECT id,visitor_name,assigned_staff_name FROM conversations WHERE visitor_id=?').bind(visitorId).first();if(!conversation)return json({ok:true,messages:[],conversation:null});const messages=await env.DB.prepare('SELECT sender,sender_name,message,created_at FROM chat_messages WHERE conversation_id=? ORDER BY id ASC LIMIT 150').bind(conversation.id).all();return json({ok:true,messages:messages.results||[],conversation});}
  if(path==='/api/chat/messages'&&request.method==='POST'){const payload=await parseJson(request);const visitorId=cleanText(payload?.visitor_id);const message=cleanText(payload?.message);const visitorName=cleanText(payload?.visitor_name).slice(0,80);if(!validVisitorId(visitorId)||!message)return error('Vui lòng nhập tin nhắn.');const conversation=await getOrCreateConversation(env,visitorId);const displayName=visitorName||conversation.visitor_name||'Khách hàng';if(visitorName&&visitorName!==conversation.visitor_name)await env.DB.prepare('UPDATE conversations SET visitor_name=? WHERE id=?').bind(visitorName,conversation.id).run();await env.DB.prepare('INSERT INTO chat_messages(conversation_id,sender,sender_name,message) VALUES (?,?,?,?)').bind(conversation.id,'visitor',displayName,message).run();await env.DB.prepare('UPDATE conversations SET last_message=?,last_message_at=CURRENT_TIMESTAMP,visitor_unread=visitor_unread+1,staff_unread=staff_unread+1 WHERE id=?').bind(message,conversation.id).run();return json({ok:true,conversation:{id:conversation.id,visitor_name:displayName}},{status:201});}
  return null;
}
async function assertOwner(request,env){const session=await requireSession(request,env);return session&&session.role==='owner'?session:null;}
async function assertStaff(request,env){const session=await requireSession(request,env);return session&&['owner','staff'].includes(session.role)?session:null;}
function makeFallbackReply(history,conversation,inventory){const last=[...history].reverse().find(item=>item.sender==='visitor')?.message||'';const lower=String(last).toLowerCase();const name=conversation?.visitor_name?`Anh/chị ${conversation.visitor_name}`:'Anh/chị';if(/tra gop|gop|no xau|ho so|tra truoc/.test(lower))return `${name} ơi, Tâm An đã nhận thông tin. Em sẽ kiểm tra mẫu xe và hồ sơ thực tế rồi tư vấn mức trả trước phù hợp; bên em không cam kết duyệt khi chưa kiểm tra đầy đủ.`;if(/gia|bao nhieu|khuyen mai|uu dai/.test(lower))return `${name} ơi, em sẽ kiểm tra đúng phiên bản và chương trình ưu đãi đang áp dụng trước khi báo chi tiết cho mình. Anh/chị cho em xin mẫu xe hoặc màu xe đang quan tâm nhé.`;const choices=inventory.slice(0,3).map(item=>item.name).join(', ');return `${name} ơi, em đã nhận tin nhắn. Tâm An đang có thể tư vấn các mẫu như ${choices||'xe tại showroom'}; anh/chị cho em xin nhu cầu hoặc mẫu xe muốn xem để em hỗ trợ chính xác nhé.`;}
function makeAiPrompt(history,conversation,inventory){const messages=history.map(item=>`${item.sender==='visitor'?conversation?.visitor_name||'Khách hàng':item.sender_name||'Nhân viên'}: ${item.message}`).join('\n');const stock=inventory.map(item=>`- ${item.name} (${item.status==='incoming'?'sắp về':'còn hàng'}${item.show_price&&Number(item.price)?`, giá ${item.price} VND`:''}${Number(item.installment_from)?`, trả góp từ ${item.installment_from} VND`:''})`).join('\n');return `Bạn là trợ lý soạn tin cho nhân viên Xe Máy Tâm An Nomura ở Hải Phòng. Soạn MỘT câu trả lời tiếng Việt lịch sự, 1-3 câu ngắn, xưng em với khách. Chỉ gợi ý cho nhân viên xem và sửa trước khi gửi. Không tự hứa duyệt trả góp, không khẳng định nợ xấu được duyệt, không tự bịa giá/ưu đãi/thông số. Với trả góp, luôn nói cần kiểm tra hồ sơ thực tế. Nếu thiếu thông tin, hỏi 1 câu ngắn để làm rõ.\n\nKho xe tham chiếu:\n${stock||'Chưa có dữ liệu kho xe'}\n\nĐoạn hội thoại:\n${messages||'Khách chưa nhắn nội dung'}`;}
async function handleAdmin(request,env,url){const path=url.pathname;const session=await assertStaff(request,env);if(!session)return error('Bạn chưa đăng nhập.',401);
  if(path==='/api/admin/settings'&&request.method==='GET'){if(session.role!=='owner')return error('Bạn không có quyền chỉnh nội dung website.',403);return json({ok:true,settings:await getSettings(env)});}
  if(path==='/api/admin/settings'&&request.method==='PUT'){if(session.role!=='owner')return error('Bạn không có quyền chỉnh nội dung website.',403);const payload=await parseJson(request);if(!payload)return error('Dữ liệu không hợp lệ.');const settings=normalizeSettings(payload);await env.DB.prepare('UPDATE site_settings SET data=?,updated_at=CURRENT_TIMESTAMP WHERE id=1').bind(JSON.stringify(settings)).run();return json({ok:true,settings});}
  if(path==='/api/admin/bikes'&&request.method==='GET'){const result=await env.DB.prepare('SELECT * FROM bikes ORDER BY updated_at DESC,id DESC').all();return json({ok:true,bikes:(result.results||[]).map(rowToBike)});}
  if(path==='/api/admin/bikes'&&request.method==='POST'){const payload=await parseJson(request);if(!payload)return error('Dữ liệu không hợp lệ.');const bike=normalizeBike(payload);if(!bike.name)return error('Vui lòng nhập tên xe.');const duplicate=await env.DB.prepare('SELECT id FROM bikes WHERE slug=? LIMIT 1').bind(bike.slug).first();if(duplicate)bike.slug=`${bike.slug}-${Date.now().toString().slice(-5)}`;const insert=await env.DB.prepare(`INSERT INTO bikes(slug,name,brand,category,price,msrp,year,mileage,engine,color,color_variants,documents,status,description,images,featured,sort_order,installment_from,bad_debt_down_payment,show_price,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)`).bind(bike.slug,bike.name,bike.brand,bike.category,bike.price,bike.msrp,bike.year,bike.mileage,bike.engine,bike.color,JSON.stringify(bike.color_variants),bike.documents,bike.status,bike.description,JSON.stringify(bike.images),bike.featured,bike.sort_order,bike.installment_from,bike.bad_debt_down_payment,bike.show_price).run();return json({ok:true,id:insert.meta.last_row_id},{status:201});}
  const bikeMatch=path.match(/^\/api\/admin\/bikes\/(\d+)$/);
  if(bikeMatch&&request.method==='PUT'){const id=Number(bikeMatch[1]);const old=await env.DB.prepare('SELECT * FROM bikes WHERE id=?').bind(id).first();if(!old)return error('Không tìm thấy xe.',404);const payload=await parseJson(request);if(!payload)return error('Dữ liệu không hợp lệ.');const bike=normalizeBike(payload,rowToBike(old));if(!bike.name)return error('Vui lòng nhập tên xe.');const duplicate=await env.DB.prepare('SELECT id FROM bikes WHERE slug=? AND id!=?').bind(bike.slug,id).first();if(duplicate)bike.slug=`${bike.slug}-${id}`;await env.DB.prepare(`UPDATE bikes SET slug=?,name=?,brand=?,category=?,price=?,msrp=?,year=?,mileage=?,engine=?,color=?,color_variants=?,documents=?,status=?,description=?,images=?,featured=?,sort_order=?,installment_from=?,bad_debt_down_payment=?,show_price=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(bike.slug,bike.name,bike.brand,bike.category,bike.price,bike.msrp,bike.year,bike.mileage,bike.engine,bike.color,JSON.stringify(bike.color_variants),bike.documents,bike.status,bike.description,JSON.stringify(bike.images),bike.featured,bike.sort_order,bike.installment_from,bike.bad_debt_down_payment,bike.show_price,id).run();return json({ok:true});}
  if(bikeMatch&&request.method==='DELETE'){if(session.role!=='owner')return error('Nhân viên không có quyền xoá xe.',403);await env.DB.prepare('DELETE FROM bikes WHERE id=?').bind(Number(bikeMatch[1])).run();return json({ok:true});}
  if(path==='/api/admin/leads'&&request.method==='GET'){const result=await env.DB.prepare('SELECT * FROM leads ORDER BY id DESC LIMIT 300').all();return json({ok:true,leads:result.results||[]});}
  if(path==='/api/admin/upload'&&request.method==='POST'){const contentType=request.headers.get('content-type')||'';const size=Number(request.headers.get('content-length')||0);if(!contentType.startsWith('image/'))return error('Chỉ nhận file ảnh.');if(size>8*1024*1024)return error('Ảnh tối đa 8MB.');const sourceName=decodeURIComponent(request.headers.get('x-file-name')||'xe-may.jpg');const extension=(sourceName.split('.').pop()||'jpg').toLowerCase();if(!MIME[extension])return error('Định dạng ảnh chưa hỗ trợ.');const key=`uploads/${Date.now()}-${crypto.randomUUID().slice(0,8)}-${sourceName.replace(/[^a-zA-Z0-9._-]/g,'-').slice(-80)}`;await env.IMAGES.put(key,request.body,{httpMetadata:{contentType:MIME[extension]}});return json({ok:true,url:`/media/${encodeURIComponent(key)}`},{status:201});}
  // Promotions: owner only
  if(path==='/api/admin/promotions'&&request.method==='GET'){if(session.role!=='owner')return error('Bạn không có quyền quản lý khuyến mại.',403);const result=await env.DB.prepare('SELECT * FROM promotions ORDER BY updated_at DESC,id DESC').all();return json({ok:true,promotions:(result.results||[]).map(rowToPromotion)});}
  if(path==='/api/admin/promotions'&&request.method==='POST'){if(session.role!=='owner')return error('Bạn không có quyền quản lý khuyến mại.',403);const data=normalizePromo(await parseJson(request)||{});if(!data.title||!data.description)return error('Vui lòng nhập tiêu đề và nội dung khuyến mại.');const row=await env.DB.prepare('INSERT INTO promotions(title,description,image_url,active,sort_order) VALUES(?,?,?,?,?)').bind(data.title,data.description,data.image_url,data.active,data.sort_order).run();return json({ok:true,id:row.meta.last_row_id},{status:201});}
  const promoMatch=path.match(/^\/api\/admin\/promotions\/(\d+)$/);
  if(promoMatch&&request.method==='PUT'){if(session.role!=='owner')return error('Bạn không có quyền quản lý khuyến mại.',403);const data=normalizePromo(await parseJson(request)||{});if(!data.title||!data.description)return error('Vui lòng nhập tiêu đề và nội dung khuyến mại.');await env.DB.prepare('UPDATE promotions SET title=?,description=?,image_url=?,active=?,sort_order=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(data.title,data.description,data.image_url,data.active,data.sort_order,Number(promoMatch[1])).run();return json({ok:true});}
  if(promoMatch&&request.method==='DELETE'){if(session.role!=='owner')return error('Bạn không có quyền xoá.',403);await env.DB.prepare('DELETE FROM promotions WHERE id=?').bind(Number(promoMatch[1])).run();return json({ok:true});}
  // Accessories: staff can add/edit, owner can delete
  if(path==='/api/admin/accessories'&&request.method==='GET'){const result=await env.DB.prepare('SELECT * FROM accessories ORDER BY updated_at DESC,id DESC').all();return json({ok:true,accessories:(result.results||[]).map(rowToAccessory)});}
  if(path==='/api/admin/accessories'&&request.method==='POST'){const data=normalizeAccessory(await parseJson(request)||{});if(!data.name)return error('Vui lòng nhập tên phụ kiện.');const row=await env.DB.prepare('INSERT INTO accessories(name,category,price,description,image_url,active,sort_order) VALUES(?,?,?,?,?,?,?)').bind(data.name,data.category,data.price,data.description,data.image_url,data.active,data.sort_order).run();return json({ok:true,id:row.meta.last_row_id},{status:201});}
  const accessoryMatch=path.match(/^\/api\/admin\/accessories\/(\d+)$/);
  if(accessoryMatch&&request.method==='PUT'){const data=normalizeAccessory(await parseJson(request)||{});if(!data.name)return error('Vui lòng nhập tên phụ kiện.');await env.DB.prepare('UPDATE accessories SET name=?,category=?,price=?,description=?,image_url=?,active=?,sort_order=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(data.name,data.category,data.price,data.description,data.image_url,data.active,data.sort_order,Number(accessoryMatch[1])).run();return json({ok:true});}
  if(accessoryMatch&&request.method==='DELETE'){if(session.role!=='owner')return error('Nhân viên không có quyền xoá phụ kiện.',403);await env.DB.prepare('DELETE FROM accessories WHERE id=?').bind(Number(accessoryMatch[1])).run();return json({ok:true});}
  if(path==='/api/admin/analytics'&&request.method==='GET'){if(session.role!=='owner')return error('Bạn không có quyền xem thống kê.',403);const result=await env.DB.prepare(`SELECT day,COUNT(*) AS views,COUNT(DISTINCT visitor_hash) AS visitors FROM analytics_visits WHERE day>=date('now','-6 day') GROUP BY day ORDER BY day DESC`).all();return json({ok:true,rows:result.results||[]});}
  if(path==='/api/admin/chats'&&request.method==='GET'){const result=await env.DB.prepare('SELECT id,visitor_name,last_message,last_message_at,staff_unread AS unread,assigned_staff_name FROM conversations ORDER BY last_message_at DESC LIMIT 150').all();return json({ok:true,conversations:result.results||[]});}
  const aiMatch=path.match(/^\/api\/admin\/chat-ai-suggest\/([a-zA-Z0-9-]+)$/);
  if(aiMatch&&request.method==='POST'){const id=aiMatch[1];const conversation=await env.DB.prepare('SELECT visitor_name FROM conversations WHERE id=?').bind(id).first();if(!conversation)return error('Không tìm thấy cuộc trò chuyện.',404);const result=await env.DB.prepare('SELECT sender,sender_name,message FROM chat_messages WHERE conversation_id=? ORDER BY id DESC LIMIT 12').bind(id).all();const history=(result.results||[]).reverse();const inventory=await env.DB.prepare(`SELECT name,status,show_price,price,installment_from,bad_debt_down_payment FROM bikes WHERE status IN ('in_stock','incoming') ORDER BY featured DESC,sort_order ASC,id DESC LIMIT 12`).all();const fallback=makeFallbackReply(history,conversation,inventory.results||[]);if(!env.GEMINI_API_KEY)return json({ok:true,suggestion:fallback,provider:'Mẫu tư vấn nội bộ',configured:false});const prompt=makeAiPrompt(history,conversation,inventory.results||[]);try{const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(env.GEMINI_MODEL||'gemini-3.1-flash-lite')}:generateContent?key=${encodeURIComponent(env.GEMINI_API_KEY)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:0.35,maxOutputTokens:220}})});const body=await response.json().catch(()=>({}));const suggestion=body?.candidates?.[0]?.content?.parts?.map(part=>part.text||'').join('').trim();if(!response.ok||!suggestion)throw new Error(body?.error?.message||'AI chưa phản hồi');return json({ok:true,suggestion:suggestion.slice(0,1200),provider:'Gemini',configured:true});}catch(cause){return json({ok:true,suggestion:fallback,provider:'Mẫu tư vấn nội bộ',configured:false,notice:'AI tạm thời chưa phản hồi; đã tạo gợi ý cơ bản.'});}}
  const chatMatch=path.match(/^\/api\/admin\/chats\/([a-zA-Z0-9-]+)$/);
  if(chatMatch&&request.method==='GET'){const id=chatMatch[1];const existing=await env.DB.prepare('SELECT id,visitor_name,assigned_staff_name FROM conversations WHERE id=?').bind(id).first();if(!existing)return error('Không tìm thấy cuộc trò chuyện.',404);if(!existing.assigned_staff_name)await env.DB.prepare('UPDATE conversations SET assigned_staff_name=?,assigned_staff_id=? WHERE id=?').bind(session.name,session.staff_id||null,id).run();await env.DB.prepare('UPDATE conversations SET visitor_unread=0,staff_unread=0 WHERE id=?').bind(id).run();const result=await env.DB.prepare('SELECT sender,sender_name,message,created_at FROM chat_messages WHERE conversation_id=? ORDER BY id ASC LIMIT 200').bind(id).all();return json({ok:true,conversation:{...existing,assigned_staff_name:existing.assigned_staff_name||session.name},messages:result.results||[]});}
  if(chatMatch&&request.method==='POST'){const body=await parseJson(request);const message=cleanText(body?.message);if(!message)return error('Vui lòng nhập câu trả lời.');const id=chatMatch[1];const existing=await env.DB.prepare('SELECT id FROM conversations WHERE id=?').bind(id).first();if(!existing)return error('Không tìm thấy cuộc trò chuyện.',404);await env.DB.prepare('INSERT INTO chat_messages(conversation_id,sender,sender_name,staff_id,message) VALUES(?,?,?,?,?)').bind(id,'staff',session.name,session.staff_id||null,message).run();await env.DB.prepare('UPDATE conversations SET last_message=?,last_message_at=CURRENT_TIMESTAMP,assigned_staff_name=?,assigned_staff_id=? WHERE id=?').bind(message,session.name,session.staff_id||null,id).run();return json({ok:true,sender_name:session.name});}
  // Staff account management: owner only
  if(path==='/api/admin/staff'&&request.method==='GET'){if(session.role!=='owner')return error('Bạn không có quyền quản lý tài khoản.',403);const result=await env.DB.prepare('SELECT id,name,username,active,created_at FROM staff_accounts ORDER BY id DESC').all();return json({ok:true,staff:result.results||[]});}
  if(path==='/api/admin/staff'&&request.method==='POST'){if(session.role!=='owner')return error('Bạn không có quyền quản lý tài khoản.',403);const body=await parseJson(request);const name=cleanText(body?.name),username=cleanText(body?.username).toLowerCase().replace(/[^a-z0-9._-]/g,'').slice(0,50),password=String(body?.password||'');if(!name||username.length<3||password.length<6)return error('Nhập đầy đủ họ tên, tên đăng nhập (ít nhất 3 ký tự) và mật khẩu (ít nhất 6 ký tự).');const password_hash=await passwordHash(password,env.SESSION_SECRET);try{const row=await env.DB.prepare('INSERT INTO staff_accounts(name,username,password_hash) VALUES(?,?,?)').bind(name,username,password_hash).run();return json({ok:true,id:row.meta.last_row_id},{status:201});}catch{return error('Tên đăng nhập này đã tồn tại.');}}
  const staffToggle=path.match(/^\/api\/admin\/staff\/(\d+)\/toggle$/);
  if(staffToggle&&request.method==='POST'){if(session.role!=='owner')return error('Bạn không có quyền quản lý tài khoản.',403);await env.DB.prepare('UPDATE staff_accounts SET active=CASE active WHEN 1 THEN 0 ELSE 1 END WHERE id=?').bind(Number(staffToggle[1])).run();return json({ok:true});}
  return error('Không tìm thấy API.',404);
}
async function handleApi(request,env,url){const path=url.pathname;
  if(path.startsWith('/media/')&&request.method==='GET'){const key=decodeURIComponent(path.slice('/media/'.length));if(!key||key.includes('..'))return error('Không tìm thấy ảnh.',404);const object=await env.IMAGES.get(key);if(!object)return error('Không tìm thấy ảnh.',404);const headers=new Headers();object.writeHttpMetadata(headers);headers.set('etag',object.httpEtag);headers.set('cache-control','public,max-age=31536000,immutable');return new Response(object.body,{headers});}
  if(path==='/api/auth/login'&&request.method==='POST'){const body=await parseJson(request);const username=cleanText(body?.username).toLowerCase();const password=String(body?.password||'');if(!password)return error('Vui lòng nhập mật khẩu.',401);if(!username&&env.ADMIN_PASSWORD&&password===env.ADMIN_PASSWORD){const token=await createSession(env.SESSION_SECRET,{role:'owner',name:'Chủ cửa hàng'});return json({ok:true,session:{authenticated:true,role:'owner',name:'Chủ cửa hàng'}},{headers:{'set-cookie':`tam_an_admin=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=43200`}});}if(username){await ensureSchema(env);const staff=await env.DB.prepare('SELECT * FROM staff_accounts WHERE username=? AND active=1').bind(username).first();if(staff&&staff.password_hash===await passwordHash(password,env.SESSION_SECRET)){const token=await createSession(env.SESSION_SECRET,{role:'staff',name:staff.name,staff_id:staff.id});return json({ok:true,session:{authenticated:true,role:'staff',name:staff.name}},{headers:{'set-cookie':`tam_an_admin=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=43200`}});}}return error('Tên đăng nhập hoặc mật khẩu không đúng.',401);}
  if(path==='/api/auth/logout'&&request.method==='POST')return json({ok:true},{headers:{'set-cookie':'tam_an_admin=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0'}});
  if(path==='/api/auth/me'&&request.method==='GET'){const session=await getSession(request,env);return json({ok:true,session:session?{authenticated:true,role:session.role,name:session.name}: {authenticated:false}});}
  await ensureSchema(env);
  const publicResult=await handlePublic(request,env,url);if(publicResult)return publicResult;
  if(path.startsWith('/api/admin/'))return handleAdmin(request,env,url);
  return error('Không tìm thấy API.',404);
}
export default { async fetch(request,env){const url=new URL(request.url);if(url.pathname.startsWith('/api/')||url.pathname.startsWith('/media/')){try{return await handleApi(request,env,url);}catch(cause){console.error(cause);return error('Máy chủ tạm thời gặp lỗi.',500);}}return env.ASSETS.fetch(request);} };
